services:
  app:
    build: ./
    environment:
      - PORT=4000
      - JWT_ACCESS_SECRET=secret
      - JWT_REFRESH_SECRET=supersecret
      - JWT_ACCESS_EXPIRES=1800
      - JWT_REFRESH_EXPIRES=2419200
      - COOKIE_EXPIRES=2419200
      - ROLES_KEY=role
      - CLIENT_URL=http://localhost:3000
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - 4000:4000
    depends_on:
      - mongo
      - mongo-express
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: root
      ME_CONFIG_MONGODB_URL: mongodb://root:root@mongo:27017/